export async function onRequest(context) {
  const { request, env } = context;

  if (request.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const { prompt, imageBase64 } = await request.json();
    
    if (!env.GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: "API Key missing in Cloudflare" }), { status: 500 });
    }

    // FIX: Changed to a valid model name
    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-lite:generateContent?key=${env.GEMINI_API_KEY}`;

    const payload = {
      system_instruction: {
        parts: [{ 
          text: "You are a world-class sustainable chef. Suggest 3 distinct healthy recipes in JSON format." 
        }]
      },
      contents: [
        {
          parts: imageBase64 
            ? [
                { inlineData: { mimeType: "image/jpeg", data: imageBase64 } },
                { text: "Analyze these ingredients: " + prompt }
              ]
            : [{ text: prompt }]
        }
      ],
      generationConfig: {
        responseMimeType: "application/json",
        temperature: 0.7
      }
    };

    const response = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });

    const result = await response.json();

    // FIX: Check for Google Errors BEFORE accessing candidates
    if (result.error) {
      return new Response(JSON.stringify({ error: result.error.message }), { status: 400 });
    }

    // FIX: Check if candidates exist at all
    if (!result.candidates || !result.candidates[0]) {
      return new Response(JSON.stringify({ error: "No recipes generated by AI" }), { status: 500 });
    }

    let textOutput = result.candidates[0].content.parts[0].text;
    
    // CLEANING: Strip markdown if Gemini sends it
    textOutput = textOutput.replace(/```json/g, '').replace(/```/g, '').trim();

    // VALIDATION: Ensure it's valid JSON before sending to frontend
    try {
      JSON.parse(textOutput); // Just a test parse
      return new Response(textOutput, {
        headers: { "Content-Type": "application/json" }
      });      
    } catch (e) {
      return new Response(JSON.stringify({ error: "AI returned invalid JSON format" }), { status: 500 });
    }

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500 });
  }
}