// Allowed origins — production domain + Cloudflare Pages preview deployments
const ALLOWED_ORIGINS = [
  'https://eatwell.world',
  'https://www.eatwell.world',
  'http://localhost:5173',  // Vite dev
  'http://localhost:8788',  // Cloudflare Pages local dev
];

const MAX_PROMPT_CHARS = 500;
const MAX_IMAGE_B64_CHARS = 7_000_000; // ~5MB of raw image data after base64 encoding

export async function onRequest(context) {
  const { request, env } = context;

  const origin = request.headers.get('Origin') || '';
  const originAllowed =
    ALLOWED_ORIGINS.includes(origin) || origin.endsWith('.pages.dev');

  const corsHeaders = {
    'Access-Control-Allow-Origin': originAllowed ? origin : 'https://eatwell.world',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };

  // Handle CORS preflight
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders });
  }

  if (request.method !== 'POST') {
    return new Response('Method not allowed', { status: 405, headers: corsHeaders });
  }

  // Reject requests from disallowed origins
  if (!originAllowed) {
    return new Response(JSON.stringify({ error: 'Forbidden' }), {
      status: 403,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }

  try {
    const body = await request.json();
    const { prompt, imageBase64 } = body;

    // Validate prompt
    if (!prompt || typeof prompt !== 'string' || prompt.trim().length === 0) {
      return new Response(JSON.stringify({ error: 'A prompt is required' }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    if (prompt.length > MAX_PROMPT_CHARS) {
      return new Response(
        JSON.stringify({ error: `Prompt must be ${MAX_PROMPT_CHARS} characters or fewer` }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Validate image size if provided
    if (imageBase64 !== undefined && imageBase64 !== null) {
      if (typeof imageBase64 !== 'string' || imageBase64.length > MAX_IMAGE_B64_CHARS) {
        return new Response(JSON.stringify({ error: 'Image is too large (max ~5MB)' }), {
          status: 413,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }
    }
    
    if (!env.GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: 'API key not configured' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // FIX: Changed to a valid model name
    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${env.GEMINI_API_KEY}`;

    const payload = {
      system_instruction: {
        parts: [{ 
          text: "You are a world-class sustainable chef. Suggest 3 distinct healthy recipes in JSON format."
          + "EACH recipe MUST contain these EXACT keys: "
          + "'title', 'description', 'cookingTime', 'difficulty', 'calories', 'servings', "
          + "'sustainabilityScore', 'ecoTip', 'ingredients' (array of strings), " 
          + "'instructions' (array of strings), and 'tags' (array of strings). "
          + "Do not omit any fields." 
        }]
      },
      contents: [
        {
          parts: imageBase64 
            ? [
                { inlineData: { mimeType: "image/jpeg", data: imageBase64 } },
                { text: "Analyze these ingredients: " + prompt }
              ]
            : [{ text: prompt }]
        }
      ],
      generationConfig: {
        responseMimeType: "application/json",
        temperature: 0.7
      }
    };

    const response = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });

    const result = await response.json();

    // FIX: Check for Google Errors BEFORE accessing candidates
    if (result.error) {
      return new Response(JSON.stringify({ error: result.error.message }), {
        status: 400,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    if (!result.candidates || !result.candidates[0]) {
      return new Response(JSON.stringify({ error: 'No recipes generated by AI' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    let textOutput = result.candidates[0].content.parts[0].text;
    
    // CLEANING: Strip markdown if Gemini sends it
    textOutput = textOutput.replace(/```json/g, '').replace(/```/g, '').trim();

    // VALIDATION: Ensure it's valid JSON before sending to frontend
    try {
      JSON.parse(textOutput);
      return new Response(textOutput, {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    } catch (e) {
      return new Response(JSON.stringify({ error: 'AI returned invalid JSON' }), {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
}