import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';

interface TermsOfServiceProps {
  onBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 animate-fadeIn">
      <button 
        onClick={onBack}
        className="group flex items-center gap-2 text-stone-500 hover:text-emerald-600 font-semibold mb-8 transition-colors"
      >
        <div className="bg-white p-2 rounded-full border border-stone-200 group-hover:border-emerald-200 shadow-sm">
          <ArrowLeft size={20} />
        </div>
        Back to Home
      </button>

      <div className="bg-white rounded-3xl shadow-xl overflow-hidden border border-stone-100 p-8 md:p-12">
        <div className="flex items-center gap-4 mb-8 border-b border-stone-100 pb-8">
          <div className="w-12 h-12 bg-emerald-100 text-emerald-600 rounded-xl flex items-center justify-center">
            <FileText size={24} />
          </div>
          <h1 className="text-3xl font-bold text-stone-900">Terms of Service</h1>
        </div>

        <div className="prose prose-stone max-w-none text-stone-600">
          <p className="text-sm text-stone-400 mb-6">Last Updated: May 15, 2025</p>

          <p className="mb-6">
            Please read these Terms of Service ("Terms") carefully before using the <strong>eatwell.world</strong> website operated by Eatwell World Inc.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">1. Acceptance of Terms</h3>
          <p className="mb-4">
            By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">2. Description of Service</h3>
          <p className="mb-4">
            Eatwell.world provides an AI-powered platform that generates recipes and sustainability insights based on user inputs and images. The Service is provided for informational and educational purposes only.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">3. AI Disclaimer</h3>
          <div className="bg-orange-50 border-l-4 border-orange-400 p-4 mb-4 text-stone-700 italic">
            <p>
              <strong>Important:</strong> The recipes, nutritional information, and sustainability scores generated by our AI are estimates. AI models can occasionally produce incorrect or misleading information.
            </p>
          </div>
          <p className="mb-4">
             You should verify important information, especially regarding food allergies, dietary restrictions, and food safety practices. We are not responsible for the outcome of any recipe tried from this website.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">4. Medical Disclaimer</h3>
          <p className="mb-4">
            The content on eatwell.world is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or dietary needs.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">5. User Conduct</h3>
          <p className="mb-4">
            You agree not to use the Service to:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Upload images that are illegal, offensive, or violate the rights of others.</li>
            <li>Attempt to reverse engineer or interfere with the proper working of the Service.</li>
            <li>Use the Service for any commercial purpose without our express written consent.</li>
          </ul>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">6. Intellectual Property</h3>
          <p className="mb-4">
            The Service and its original content (excluding user-generated content), features, and functionality are and will remain the exclusive property of Eatwell World Inc. and its licensors.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">7. Limitation of Liability</h3>
          <p className="mb-4">
            In no event shall Eatwell World Inc., nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">8. Governing Law</h3>
          <p className="mb-4">
            These Terms shall be governed and construed in accordance with the laws of the United States, without regard to its conflict of law provisions.
          </p>

          <h3 className="text-xl font-bold text-stone-900 mt-8 mb-4">9. Contact Us</h3>
          <p className="mb-4">
            If you have any questions about these Terms, please contact us at: <br/>
            <span className="text-emerald-600 font-semibold">legal@eatwell.world</span>
          </p>
        </div>
      </div>
    </div>
  );
};